FROM thejunys/jdk:latest

MAINTAINER <thejunys@naver.com>

COPY ./build/libs/blackjack-backend-0.0.1-SNAPSHOT.jar app.jar

ARG ACTIVE
ENV SPRING_PROFILES_ACTIVE=ACTIVE

RUN echo $ACTIVE
RUN echo $SPRING_PROFILES_ACTIVE

ENTRYPOINT ["java", "-jar", "/app.jar", "&"]
