spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb:3306/blackjack?characterEncoding=UTF-8&serverTimezone=UTC
    username: blackjack
    password: blackjack
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      url: redis://mypass@redis:6379/0
